import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import ReactQueryProviders from "../share/Providers/react-query-provider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const pretendard = localFont({
  src: "../public/static/font/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`${pretendard.variable}`}>
      <body className={`${pretendard.className} overflow-hidden`}>
        <ReactQueryProviders>{children}</ReactQueryProviders>
      </body>
    </html>
  );
}
