import { ModalProvider } from "@/share/Providers/ModalContext";
import type { Metadata } from "next";
import localFont from "next/font/local";
import ReactQueryProviders from "../share/Providers/TantackContext";
import "./globals.css";

const pretendard = localFont({
  src: "../public/static/font/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`${pretendard.variable}`}>
      <body className={`${pretendard.className} overflow-hidden`}>
        <ReactQueryProviders>
          <ModalProvider>{children} </ModalProvider>
        </ReactQueryProviders>
      </body>
    </html>
  );
}
